package com.geiyepa.demo.entity;


public class paper {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.id
     *
     * @mbg.generated
     */

    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.typeandyear
     *
     * @mbg.generated
     */
    private String typeandyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.releasetime
     *
     * @mbg.generated
     */
    private String releasetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.link
     *
     * @mbg.generated
     */
    private String link;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.abstractContext
     *
     * @mbg.generated
     */
    private String abstractcontext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.keyword
     *
     * @mbg.generated
     */
    private String keyword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.id
     *
     * @return the value of paper.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.id
     *
     * @param id the value for paper.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.typeandyear
     *
     * @return the value of paper.typeandyear
     *
     * @mbg.generated
     */
    public String getTypeandyear() {
        return typeandyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.typeandyear
     *
     * @param typeandyear the value for paper.typeandyear
     *
     * @mbg.generated
     */
    public void setTypeandyear(String typeandyear) {
        this.typeandyear = typeandyear == null ? null : typeandyear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.releasetime
     *
     * @return the value of paper.releasetime
     *
     * @mbg.generated
     */
    public String getReleasetime() {
        return releasetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.releasetime
     *
     * @param releasetime the value for paper.releasetime
     *
     * @mbg.generated
     */
    public void setReleasetime(String releasetime) {
        this.releasetime = releasetime == null ? null : releasetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.link
     *
     * @return the value of paper.link
     *
     * @mbg.generated
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.link
     *
     * @param link the value for paper.link
     *
     * @mbg.generated
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.title
     *
     * @return the value of paper.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.title
     *
     * @param title the value for paper.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.abstractContext
     *
     * @return the value of paper.abstractContext
     *
     * @mbg.generated
     */
    public String getAbstractcontext() {
        return abstractcontext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.abstractContext
     *
     * @param abstractcontext the value for paper.abstractContext
     *
     * @mbg.generated
     */
    public void setAbstractcontext(String abstractcontext) {
        this.abstractcontext = abstractcontext == null ? null : abstractcontext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.keyword
     *
     * @return the value of paper.keyword
     *
     * @mbg.generated
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.keyword
     *
     * @param keyword the value for paper.keyword
     *
     * @mbg.generated
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    @Override
    public String toString() {
        return "paper{" +
                "id=" + id +
                ", typeandyear='" + typeandyear + '\'' +
                ", releasetime='" + releasetime + '\'' +
                ", link='" + link + '\'' +
                ", title='" + title + '\'' +
                ", abstractcontext='" + abstractcontext + '\'' +
                ", keyword='" + keyword + '\'' +
                '}';
    }
}