package com.geiyepa.demo.mapper;

import com.geiyepa.demo.bean.keywordanalysis;

import java.util.List;

public interface keywordanalysisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywordanalysis
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywordanalysis
     *
     * @mbg.generated
     */
    int insert(keywordanalysis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywordanalysis
     *
     * @mbg.generated
     */
    int insertSelective(keywordanalysis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywordanalysis
     *
     * @mbg.generated
     */
    keywordanalysis selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywordanalysis
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(keywordanalysis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keywordanalysis
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(keywordanalysis record);

    List<keywordanalysis> getTopKeywordByYear(String year);
}