spring:
  datasource:
    url: jdbc:mysql://118.25.6.96:3306/paper_crawling?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: "!Cjx13616071299"
    driver-class-name: com.mysql.jdbc.Driver

#配置mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true

