package com.geiyepa.demo.bean;

import org.springframework.context.annotation.Bean;


public class paper {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.id
     *
     * @mbg.generated
     */

    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.typeandyear
     *
     * @mbg.generated
     */
    private String typeandyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.releasetime
     *
     * @mbg.generated
     */
    private String releasetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column paper.link
     *
     * @mbg.generated
     */
    private String link;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.id
     *
     * @return the value of paper.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.id
     *
     * @param id the value for paper.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.typeandyear
     *
     * @return the value of paper.typeandyear
     *
     * @mbg.generated
     */
    public String getTypeandyear() {
        return typeandyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.typeandyear
     *
     * @param typeandyear the value for paper.typeandyear
     *
     * @mbg.generated
     */
    public void setTypeandyear(String typeandyear) {
        this.typeandyear = typeandyear == null ? null : typeandyear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.releasetime
     *
     * @return the value of paper.releasetime
     *
     * @mbg.generated
     */
    public String getReleasetime() {
        return releasetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.releasetime
     *
     * @param releasetime the value for paper.releasetime
     *
     * @mbg.generated
     */
    public void setReleasetime(String releasetime) {
        this.releasetime = releasetime == null ? null : releasetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column paper.link
     *
     * @return the value of paper.link
     *
     * @mbg.generated
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column paper.link
     *
     * @param link the value for paper.link
     *
     * @mbg.generated
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }
}