package com.geiyepa.demo.bean;

public class keywordanalysis {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keywordanalysis.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keywordanalysis.keyword
     *
     * @mbg.generated
     */
    private String keyword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keywordanalysis.frequency
     *
     * @mbg.generated
     */
    private Integer frequency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keywordanalysis.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column keywordanalysis.publishyear
     *
     * @mbg.generated
     */
    private String publishyear;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keywordanalysis.id
     *
     * @return the value of keywordanalysis.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keywordanalysis.id
     *
     * @param id the value for keywordanalysis.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keywordanalysis.keyword
     *
     * @return the value of keywordanalysis.keyword
     *
     * @mbg.generated
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keywordanalysis.keyword
     *
     * @param keyword the value for keywordanalysis.keyword
     *
     * @mbg.generated
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keywordanalysis.frequency
     *
     * @return the value of keywordanalysis.frequency
     *
     * @mbg.generated
     */
    public Integer getFrequency() {
        return frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keywordanalysis.frequency
     *
     * @param frequency the value for keywordanalysis.frequency
     *
     * @mbg.generated
     */
    public void setFrequency(Integer frequency) {
        this.frequency = frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keywordanalysis.type
     *
     * @return the value of keywordanalysis.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keywordanalysis.type
     *
     * @param type the value for keywordanalysis.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column keywordanalysis.publishyear
     *
     * @return the value of keywordanalysis.publishyear
     *
     * @mbg.generated
     */
    public String getPublishyear() {
        return publishyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column keywordanalysis.publishyear
     *
     * @param publishyear the value for keywordanalysis.publishyear
     *
     * @mbg.generated
     */
    public void setPublishyear(String publishyear) {
        this.publishyear = publishyear == null ? null : publishyear.trim();
    }
}