-- phpMyAdmin SQL Dump
-- version 4.1.14
-- http://www.phpmyadmin.net
--
-- 主機: 127.0.0.1
-- 產生時間： 2021 �?03 ??22 ??17:27
-- 伺服器版本: 5.6.17
-- PHP 版本： 5.5.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- 資料庫： `paper`
--

-- --------------------------------------------------------

--
-- 資料表結構 `papers`
--

CREATE TABLE IF NOT EXISTS `papers` (
  `name` varchar(100) NOT NULL,
  `year` varchar(50) NOT NULL,
  `keyword` varchar(100) NOT NULL,
  `link` varchar(200) NOT NULL,
  `digest` varchar(20000) NOT NULL,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- 資料表的匯出資料 `papers`
--

INSERT INTO `papers` (`name`, `year`, `keyword`, `link`, `digest`) VALUES
('"3-D Motion and Structure from 2-D Motion Causally Integrated over Time: Implementation"', '"ECCV 2000"', '["Pattern Anal", "Rigid Motion", "Motion Error", "Minimal Realization", "Correspondence Problem"]', '"https://doi.org/10.1007/3-540-45053-X_47"', '"The causal estimation of three-dimensional motion from a sequence of two-dimensional images can be posed as a nonlinear filtering problem. We describe the implementation of an algorithm whose uniform observability, minimal realization and stability have been proven analytically in [5]. We discuss a scheme for handling occlusions, drift in the scale factor and tuning of the filter. We also present an extension to partially calibrated camera models and prove its observability. We report the performance of our implementation on a few long sequences of real images. More importantly, however, we have made our real-time implementation - which runs on a personal computer - available to the public for first-hand testing."'),
('"3D Reconstruction from Tangent-of-Sight Measurements of a Moving Object Seen from a Moving Camera"', '"ECCV 2000"', '[]', '"https://doi.org/10.1007/3-540-45054-8_40"', '"Consider the situation of a monocular image sequence with known ego-motion observing a 3D point moving simultaneously but along a path of up to second order, i.e. it can trace a line in 3D or a conic shaped path. We wish to reconstruct the 3D path from the projection of the tangent to the path at each time instance. This problem is analogue to the \\u201ctrajectory triangulation\\u201d of lines and conic sections recently introduced in [1,3], but instead of observing a point projection we observe a tangent projection and thus obtain a far simpler solution to the problem."'),
('"A General Method for Unsupervised Segmentation of Images Using a Multiscale Approach"', '"ECCV 2000"', '["Image Segmentation", "Cluster Centre", "Coarse Scale", "Shift Vector", "Texture Segmentation"]', '"https://doi.org/10.1007/3-540-45053-X_5"', '"We propose a general unsupervised multiscale approach towards image segmentation. The novelty of our method is based on the following points: firstly, it is general in the sense of being independent of the feature extraction process; secondly, it is unsupervised in that the number of classes is not assumed to be known a priori; thirdly, it is flexible as the decomposition sensitivity can be robustly adjusted to produce segmentations into varying number of classes and fourthly, it is robust through the use of the mean shift clustering and Bayesian multiscale processing. Clusters in the joint spatio-feature domain are assumed to be properties of underlying classes, the recovery of which is achieved by the use of the mean shift procedure, a robust non-parametric decomposition method. The subsequent classification procedure consists of Bayesian multiscale processing which models the inherent uncertainty in the joint specification of class and position via a Multiscale Random Field model which forms a Markov Chain in scale. At every scale, the segmentation map and model parameters are determined by sampling from their conditional posterior distributions using Markov Chain Monte Carlo simulations with stochastic relaxation. The method is then applied to perform both colour and texture segmentation. Experimental results show the proposed method performs well even for complicated images."'),
('"A Minimal Set of Constraints for the Trifocal Tensor"', '"ECCV 2000"', '["Image Plane", "Null Space", "Fundamental Matrix", "Fundamental Matrice", "Double Root"]', '"https://doi.org/10.1007/3-540-45054-8_6"', '"In this paper we derive a minimal set of sufficient constraints in order for 27 numbers to constitute a trifocal tensor. It is shown that, in general, eight nonlinear algebraic constraints are enough. This result is in accordance with the theoretically expected number of eight independent constraints and novel since the to date known sets of sufficient constraints contain at least 12 conditions. Up to now, research and formulation of constraints for the trifocal tensor has concentrated mainly on the correlation slices and has produced sets of constraints that are neither minimal (\\u2265 12) nor independent. We show that by turning attention from correlation to homographic slices, simple geometric considerations yield the desired result. Having the minimal set of constraints is important for constrained estimation of the tensor, as well as for deepening the understanding of the multiple view relations that are valid in the projective framework."'),
('"A Physically-Based Statistical Deformable Model for Brain Image Analysis"', '"ECCV 2000"', '["Registration Error", "Deformable Model", "Brain Surface", "Training Population", "Rigid Registrati', '"https://doi.org/10.1007/3-540-45053-X_34"', '"A probabilistic deformable model for the representation of brain structures is described. The statistically learned deformable model represents the relative location of head (skull and scalp) and brain surfaces in Magnetic Resonance Images (MRIs) and accommodates their significant variability across different individuals. The head and brain surfaces of each volume are parameterized by the amplitudes of the vibration modes of a deformable spherical mesh. For a given MRI in the training set, a vector containing the largest vibration modes describing the head and the brain is created. This random vector is statistically constrained by retaining the most significant variation modes of its Karhunen-Loeve expansion on the training population. By these means, the conjunction of surfaces are deformed according to the anatomical variability observed in the training set. Two applications of the probabilistic deformable model are presented: the deformable model-based registration of 3D multimodal (MR/SPECT) brain images without removing non-brain structures and the segmentation of the brain in MRI using the probabilistic constraints embedded in the deformable model. The multi-object deformable model may be considered as a first step towards the development of a general purpose probabilistic anatomical brain atlas."'),
('"A Probabilistic Background Model for Tracking"', '"ECCV 2000"', '["Partition Function", "Hide Markov Model", "Importance Sampling", "Observation Window", "Shadow Reg', '"https://doi.org/10.1007/3-540-45053-X_22"', '"A new probabilistic background model based on a Hidden Markov Model is presented. The hidden states of the model enable discrimination between foreground, background and shadow. This model functions as a low level process for a car tracker. A particle filter is employed as a stochastic filter for the car tracker. The use of a particle filter allows the incorporation of the information from the low level process via importance sampling. A novel observation density for the particle filter which models the statistical dependence of neighboring pixels based on a Markov random field is presented. The effectiveness of both the low level process and the observation likelihood are demonstrated."'),
('"A Probabilistic Interpretation of the Saliency Network"', '"ECCV 2000"', '["Feature Point", "Length Distribution", "Human Visual System", "Perceptual Organization", "Probabil', '"https://doi.org/10.1007/3-540-45053-X_17"', '"The calculation of salient structures is one of the early and basic ideas of perceptual organization in Computer Vision. Saliency algorithms aim to find image curves, maximizing some deterministic quality measure which grows with the length of the curve, its smoothness, and its continuity. This note proposes a modified saliency estimation mechanism, which is based on probabilistically specified grouping cues and on length estimation. In the context of the proposed method, the wellknown saliency mechanism, proposed by Shaashua and Ullman [SU88], may be interpreted as a process trying to detect the curve with maximal expected length."'),
('"A Probabilistic Sensor for the Perception and the Recognition of Activities"', '"ECCV 2000"', '["Hide Markov Model", "Recognition Rate", "Activity Recognition", "Probabilistic Sensor", "Signal De', '"https://doi.org/10.1007/3-540-45054-8_32"', '"This paper presents a new technique for the perception and recognition of activities using statistical descriptions of their spatiotemporal properties. A set of motion energy receptive fields is designed in order to sample the power spectrum of a moving texture. Their structure relates to the spatio-temporal energy models of Adelson and Bergen where measures of local visual motion information are extracted by comparing the outputs of a triad of Gabor energy filters. Then the probability density function required for Bayes rule is estimated for each class of activity by computing multi-dimensional histograms from the outputs from the set of receptive fields. The perception of activities is achieved according to Bayes rule. The result at each instant of time is the map of the conditional probabilities that each pixel belongs to each one of the activities of the training set. Since activities are perceived over a short integration time, a temporal analysis of outputs is done using Hidden Markov Models."'),
('"A Six Point Solution for Structure and Motion"', '"ECCV 2000"', '["Image Point", "Singular Vector", "Geometric Error", "Point Solution", "Bundle Adjustment"]', '"https://doi.org/10.1007/3-540-45054-8_41"', '"The paper has two main contributions: The first is a set of methods for computing structure and motion for m\\u2265 3 views of 6 points. It is shown that a geometric image error can be minimized over all views by a simple three parameter numerical optimization. Then, that an algebraic image error can be minimized over all views by computing the solution to a cubic in one variable. Finally, a minor point, is that this \\u201cquasi-linear\\u201d linear solution enables a more concise algorithm, than any given previously, for the reconstruction of 6 points in 3 views."'),
('"A Unifying Theory for Central Panoramic Systems and Practical Implications"', '"ECCV 2000"', '["Great Circle", "Image Center", "Stereographic Projection", "Perspective Projection", "Parabolic Mi', '"https://doi.org/10.1007/3-540-45053-X_29"', '"Omnidirectional vision systems can provide panoramic alertness in surveillance, improve navigational capabilities, and produce panoramic images for multimedia. Catadioptric realizations of omnidirectional vision combine reflective surfaces and lenses. A particular class of them, the central panoramic systems, preserve the uniqueness of the projection viewpoint. In fact, every central projection system including the well known perspective projection on a plane falls into this category."');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
